default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rails-react-webpack-demo_development

test:
  <<: *default
  database: rails-react-webpack-demo_test

production:
  <<: *default
  database: rails-react-webpack-demo_production
